version: "3"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: "start-dev"
    ports:
      - 8081:8080
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
